### ISSUE TITLE
关于css的3d展示效果 perspective和transform-style

### ISSUE THREAD

**Issue by LouieXee** [LouieXie/blog#5]
随着对css3学习的深入，对页面的展示效果的自我要求也越来越高，希望能够展示更加酷炫的效果。本次主要是对3d展示效果的学习和个人想法。

主要参考的文章 [Transform-style和Perspective属性](http://www.w3cplus.com/css3/transform-basic-property.html)
## perspective和transform: perspective

这个属性主要的作用修改元素的展示效果，相当于视点相对于目标元素的一个距离。默认距离是无限远，所以目标元素看起来就像是在平面上变化。但当将其改成合适的距离是，并可以看到3d的变化效果。

举个栗子：

先看代码，首先是html代码：

``` html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>I'm louie</title>
    </head>
    <body>
        <div class="container">
            <div class="inner"></div>
        </div>
    </body>
</html>
```

然后是css代码：

``` css
.container{ width: 500px; height: 500px; border: 1px solid #000; margin: 0 auto; background-color: green;}
.inner{ width: 100%; height: 100%; background-color: tomato; position: relative;
    transform: rotateX(60deg);
    -webkit-transform: rotateX(60deg);
    -moz-transform: rotateX(60deg);
}
```

然后我们可以看到页面展示如下（以chrome为例）：
![withoutPerspective](https://raw.githubusercontent.com/LouieXie/blog/master/images/perspective1.jpg)

inner元素并没有展示出3d的效果，只是简单的在平面内变化

然后，让我们把css代码做下简单的调整：

``` css
.container{ width: 500px; height: 500px; border: 1px solid #000; margin: 0 auto; background-color: green;
    perspective: 600px;
    -webkit-perspective: 600px;
    -moz-perspective: 600px;
}
.inner{ width: 100%; height: 100%; background-color: tomato; position: relative;
    transform: rotateX(60deg);
    -webkit-transform: rotateX(60deg);
    -moz-transform: rotateX(60deg);
}
```

对！ 让我们在父元素上加上`perspective`属性，然后将其值设置为600px，先让我们看看发生了什么

![withPerspective600](https://raw.githubusercontent.com/LouieXie/blog/master/images/perspective2.jpg)

tada~ 我们看到inner元素的转动效果出现了前宽后窄的效果，有了那么一点3d的效果了。我们可以简单的理解为，我们看inner元素的视点从原先的无限远移到了距离inner元素只有600px的地方啦~ 可以看到更加精彩的效果啦~  

在做一个实验，当我们把perspective的值设置成3000，那么为如何呢？页面效果如下：

![withPerspective3000](https://raw.githubusercontent.com/LouieXie/blog/master/images/perspective3.jpg)

我们可以看到，inner元素的转动效果不如数值为600px的明显，那是因为我们的视点拉长了好多，所以看到的效果也不同了。将两者结合起来比较，应该有助于我们理解`perspective`这一值的现实意义。

而`perspective`和`transform: perspective`的区别仅仅在于前者需要设置在祖先级元素上，后者需要设置在目标元素本身上。同时需要有几个使用时需要注意的地方：
- 关于数值是否需要带单位，`transform: perspective`使用时需要带上单位，而`perspective`在IE和FireFox中同样需要带上单位，但是在Chrome中可带可不带，所以还是让我们在使用的时候带上单位吧;
- 在`transform: perspective`的使用过程中，我们需要把`perspective`写在最前面，像这样`transform: perspective(600px) rotateX(60deg)`，这样才能让其生效。
- `perspective`属性可以继承
## transform-style

先让我们上代码，html代码不变，css代码如下：

``` css
.container{ width: 500px; height: 500px; border: 1px solid #000; margin: 0 auto; background-color: green;
    transform: rotateY(80deg);
    -webkit-transform: rotateY(80deg);
    -moz-transform: rotateY(80deg);
}
.inner{ width: 100%; height: 100%; background-color: tomato; position: relative;
    transform: rotateX(60deg);
    -webkit-transform: rotateX(60deg);
    -moz-transform: rotateX(60deg);
}
```

效果如下：

![withoutTransformStyle](https://raw.githubusercontent.com/LouieXie/blog/master/images/perspective4.jpg)

你会说，诶我去，这是什么鬼，金箍棒吗

不着急，让我把css代码改成如下：

``` css
.container{ width: 500px; height: 500px; border: 1px solid #000; margin: 0 auto; background-color: green;
    transform: rotateY(80deg);
    -webkit-transform: rotateY(80deg);
    -moz-transform: rotateY(80deg);
    transform-style: preserve-3d;
    -webkit-transform-style: preserve-3d;
    -moz-transform-style: preserve-3d;
}
.inner{ width: 100%; height: 100%; background-color: tomato; position: relative;
    transform: rotateX(60deg);
    -webkit-transform: rotateX(60deg);
    -moz-transform: rotateX(60deg);
}
```

接下来就可以看到`transform-style`属性的神奇之处啦：

![withTransformStyle](https://raw.githubusercontent.com/LouieXie/blog/master/images/perspective5.jpg)

这时候我们的金箍棒变了模样，可以看到inner元素又展现出了3d的效果，当我们没设置`transform-style`属性的时候，inner元素确实已经发生了变化，但是因为没有将transform-style设置为`preserve-3d`，所以子元素的变化没有3d效果。

然后让我们区分一下`transform-style`和`perspective`的区别，首先`perspective`属性只是调整视距，只能简单的展示出前宽后窄的这么一个效果；而`transform-style`是确实实现了3d的效果。可以简单通过图4和图5的比较看出，图4即便inner元素转动了，但是依旧是在父级container平面内；而当设置了`preserve-3d`后，inner元素并脱离了父级container的平面，一前一后出现在container上。

同样，有几点需要注意：
- chrome、safari、FirFox等高级浏览器支持`transform-style`，IE不支持;
- 该属性只对子元素有效，无法继承到子孙元素上。
